services:
  - type: web
    name: sentinela-bot-pro
    env: python
    region: frankfurt
    buildCommand: pip install -r sistema/requirements.txt
    startCommand: cd sistema && python main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
